name: SVAutoPromote
main: fr.zankia.SVAutoPromote.SVAP
version: 0.5
description: Automagically promote player with a certain amount of time
author: zankia
depend: [Vault]

commands:
  svplayer:
    description: Plugin management command.
    aliases: [svap]
    usage: /svautopromote reload

permissions:
  svautopromote.admin:
    description: Allows managing the plugin.